-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."blossom_h.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	blossom_baby_cel={
		[0]={u=46, v=0, w=22, h=24, offsetX=10, offsetY=20, duration=0.0333333},
		scale=1
	},
	blossom_mature_cel={
		[0]={u=0, v=0, w=46, h=50, offsetX=23, offsetY=38, duration=0.0333333},
		scale=1
	},
	blossom_young_cel={
		[0]={u=40, v=50, w=30, h=28, offsetX=15, offsetY=20, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
