-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."girl.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	walking_right={
		[0]={u=294, v=0, w=64, h=196, offsetX=29, offsetY=180, duration=0.1},
		[1]={u=486, v=0, w=82, h=186, offsetX=34, offsetY=181, duration=0.1},
		[2]={u=520, v=186, w=90, h=186, offsetX=42, offsetY=181, duration=0.1},
		[3]={u=650, v=0, w=72, h=182, offsetX=35, offsetY=177, duration=0.1},
		[4]={u=700, v=182, w=72, h=182, offsetX=35, offsetY=181, duration=0.1},
		[5]={u=0, v=0, w=98, h=200, offsetX=46, offsetY=181, duration=0.1},
		[6]={u=722, v=0, w=72, h=182, offsetX=35, offsetY=177, duration=0.1},
		scale=1
	},
	walking_left={
		[0]={u=294, v=0, w=64, h=196, offsetX=35, offsetY=180, duration=0.1},
		[1]={u=486, v=0, w=82, h=186, offsetX=40, offsetY=181, duration=0.1},
		[2]={u=520, v=186, w=90, h=186, offsetX=48, offsetY=181, duration=0.1},
		[3]={u=650, v=0, w=72, h=182, offsetX=41, offsetY=177, duration=0.1},
		[4]={u=700, v=182, w=72, h=182, offsetX=41, offsetY=181, duration=0.1},
		[5]={u=0, v=0, w=98, h=200, offsetX=52, offsetY=181, duration=0.1},
		[6]={u=722, v=0, w=72, h=182, offsetX=41, offsetY=177, duration=0.1},
		scale=1, flipH=true
	},
	pickup_right={
		[0]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=0.1},
		[1]={u=794, v=0, w=86, h=156, offsetX=41, offsetY=151, duration=0.1},
		[2]={u=0, v=200, w=98, h=200, offsetX=50, offsetY=188, duration=0.1},
		[3]={u=880, v=0, w=86, h=156, offsetX=41, offsetY=151, duration=0.1},
		[4]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		[5]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		[6]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		[7]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		scale=1
	},
	pickup_left={
		[0]={u=358, v=0, w=64, h=196, offsetX=31, offsetY=184, duration=0.1},
		[1]={u=794, v=0, w=86, h=156, offsetX=39, offsetY=151, duration=0.1},
		[2]={u=0, v=200, w=98, h=200, offsetX=48, offsetY=188, duration=0.1},
		[3]={u=880, v=0, w=86, h=156, offsetX=39, offsetY=151, duration=0.1},
		[4]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		[5]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		[6]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		[7]={u=358, v=0, w=64, h=196, offsetX=33, offsetY=184, duration=100000000000.1},
		scale=1, flipH=true
	},
	planting_right={
		[0]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=0.1},
		[1]={u=880, v=156, w=86, h=156, offsetX=40, offsetY=149, duration=0.1},
		[2]={u=98, v=200, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[3]={u=98, v=0, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[4]={u=196, v=0, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[5]={u=196, v=200, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[6]={u=794, v=156, w=86, h=156, offsetX=40, offsetY=149, duration=0.1},
		[7]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		[8]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		[9]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		[10]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		scale=1
	},
	planting_left={
		[0]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=0.1},
		[1]={u=880, v=156, w=86, h=156, offsetX=40, offsetY=149, duration=0.1},
		[2]={u=98, v=200, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[3]={u=98, v=0, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[4]={u=196, v=0, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[5]={u=196, v=200, w=98, h=200, offsetX=49, offsetY=186, duration=0.1},
		[6]={u=794, v=156, w=86, h=156, offsetX=40, offsetY=149, duration=0.1},
		[7]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		[8]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		[9]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		[10]={u=392, v=196, w=64, h=196, offsetX=32, offsetY=182, duration=100000000000.1},
		scale=1, flipH=true
	},
	standing_right={
		[0]={u=456, v=196, w=64, h=196, offsetX=31, offsetY=180, duration=0.1},
		scale=1
	},
	standing_left={
		[0]={u=456, v=196, w=64, h=196, offsetX=33, offsetY=180, duration=0.1},
		scale=1, flipH=true
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
