-- Generated by Pumpkin

local data = {}
local path = ...
if type(path) ~= "string" then
	path = "."
end

data.image = love.graphics.newImage(path.."/jorj.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	chopLeft={
		[0]={u=162, v=394, w=138, h=110, offsetX=73, offsetY=108, duration=0.133333},
		[1]={u=462, v=260, w=162, h=134, offsetX=105, offsetY=132, duration=0.0666667},
		[2]={u=0, v=0, w=462, h=260, offsetX=238, offsetY=190, duration=0.0333333},
		[3]={u=0, v=260, w=204, h=128, offsetX=150, offsetY=96, duration=0.133333},
		scale=1
	},
	chopRight={
		[0]={u=204, v=504, w=138, h=110, offsetX=79, offsetY=108, duration=0.133333},
		[1]={u=0, v=394, w=162, h=134, offsetX=72, offsetY=132, duration=0.0666667},
		[2]={u=462, v=0, w=462, h=260, offsetX=238, offsetY=190, duration=0.0333333},
		[3]={u=0, v=528, w=204, h=128, offsetX=69, offsetY=96, duration=0.133333},
		scale=1
	},
	Idleleft={
		[0]={u=630, v=494, w=142, h=98, offsetX=88, offsetY=98, duration=0.2},
		[1]={u=876, v=360, w=142, h=96, offsetX=88, offsetY=96, duration=0.133333},
		scale=1
	},
	IdleRight={
		[0]={u=734, v=360, w=142, h=98, offsetX=69, offsetY=98, duration=0.2},
		[1]={u=876, v=456, w=142, h=96, offsetX=69, offsetY=96, duration=0.133333},
		scale=1
	},
	runLeft={
		[0]={u=300, v=260, w=146, h=102, offsetX=89, offsetY=99, duration=0.133333},
		[1]={u=486, v=496, w=144, h=100, offsetX=88, offsetY=98, duration=0.133333},
		[2]={u=342, v=504, w=144, h=102, offsetX=89, offsetY=99, duration=0.133333},
		[3]={u=590, v=394, w=144, h=100, offsetX=88, offsetY=99, duration=0.133333},
		scale=1
	},
	runRight={
		[0]={u=300, v=362, w=146, h=102, offsetX=72, offsetY=99, duration=0.133333},
		[1]={u=630, v=260, w=144, h=100, offsetX=70, offsetY=98, duration=0.133333},
		[2]={u=446, v=394, w=144, h=102, offsetX=70, offsetY=99, duration=0.133333},
		[3]={u=774, v=260, w=144, h=100, offsetX=70, offsetY=99, duration=0.133333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
