-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."leaf_a_cel.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	leaf_baby_cel={
		[0]={u=32, v=16, w=16, h=18, offsetX=8, offsetY=13, duration=0.0333333},
		scale=1
	},
	leaf_mature_cel={
		[0]={u=0, v=0, w=32, h=22, offsetX=17, offsetY=18, duration=0.0333333},
		scale=1
	},
	leaf_young_cel={
		[0]={u=48, v=22, w=16, h=18, offsetX=5, offsetY=15, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
