-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."leaf_c_cel.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	leaf_baby_cel={
		[0]={u=32, v=38, w=14, h=22, offsetX=5, offsetY=18, duration=0.0333333},
		scale=1
	},
	leaf_mature_cel={
		[0]={u=0, v=26, w=32, h=30, offsetX=15, offsetY=26, duration=0.0333333},
		scale=1
	},
	leaf_young_cel={
		[0]={u=0, v=0, w=34, h=26, offsetX=16, offsetY=21, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
