-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."leaf_d_cel.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	leaf_baby_cel={
		[0]={u=0, v=0, w=14, h=30, offsetX=7, offsetY=25, duration=0.0333333},
		scale=1
	},
	leaf_mature_cel={
		[0]={u=0, v=30, w=50, h=30, offsetX=26, offsetY=24, duration=0.0333333},
		scale=1
	},
	leaf_young_cel={
		[0]={u=14, v=0, w=20, h=30, offsetX=10, offsetY=25, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
