-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."leaf_e_cel.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	leaf_baby_cel={
		[0]={u=34, v=0, w=16, h=18, offsetX=8, offsetY=15, duration=0.0333333},
		scale=1
	},
	leaf_mature_cel={
		[0]={u=0, v=0, w=20, h=30, offsetX=9, offsetY=26, duration=0.0333333},
		scale=1
	},
	leaf_young_cel={
		[0]={u=0, v=30, w=18, h=30, offsetX=9, offsetY=26, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
