-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."leaf_b.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	leaf_baby={
		[0]={u=30, v=40, w=10, h=10, offsetX=6, offsetY=12, duration=0.0333333},
		scale=1
	},
	leaf_mature={
		[0]={u=14, v=46, w=16, h=18, offsetX=7, offsetY=21, duration=0.0333333},
		scale=1
	},
	leaf_young={
		[0]={u=18, v=26, w=14, h=14, offsetX=7, offsetY=16, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
