-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."leaf_b_cel.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	leaf_baby_cel={
		[0]={u=0, v=46, w=14, h=18, offsetX=8, offsetY=14, duration=0.0333333},
		scale=1
	},
	leaf_mature_cel={
		[0]={u=0, v=0, w=20, h=26, offsetX=9, offsetY=23, duration=0.0333333},
		scale=1
	},
	leaf_young_cel={
		[0]={u=0, v=26, w=18, h=20, offsetX=8, offsetY=17, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
