-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."leaf_a.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	leaf_baby={
		[0]={u=0, v=54, w=8, h=10, offsetX=5, offsetY=10, duration=0.0333333},
		scale=1
	},
	leaf_mature={
		[0]={u=32, v=0, w=26, h=16, offsetX=14, offsetY=16, duration=0.0333333},
		scale=1
	},
	leaf_young={
		[0]={u=48, v=40, w=10, h=14, offsetX=3, offsetY=14, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
