-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."/ninja.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	alleoop={
		[0]={u=0, v=0, w=34, h=34, offsetX=31, offsetY=6, duration=0.0333333},
		[1]={u=18, v=58, w=20, h=26, offsetX=21, offsetY=6, duration=0.0333333},
		[2]={u=34, v=0, w=26, h=20, offsetX=26, offsetY=1, duration=0.0333333},
		[3]={u=0, v=58, w=18, h=34, offsetX=22, offsetY=6, duration=0.0333333},
		[4]={u=34, v=20, w=24, h=18, offsetX=26, offsetY=-7, duration=0.0333333},
		[5]={u=0, v=34, w=24, h=24, offsetX=25, offsetY=-4, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
